//! Artifact emission for a proposal.
//!
//! Per Feature 1 spec: emit four artifacts to disk and return a manifest.
//!   1. `<target>.proto`        — protobuf message + service skeleton
//!   2. `<target>.sql`          — Postgres DDL
//!   3. `<target>_handler.rs`   — Axum HTTP handler skeleton
//!   4. `<target>.fga.json`     — OpenFGA policy tuples
//!
//! Per stack constraints: string templating only — no `prost-build` codegen.
//!
//! All four sit under `generated/{proposal_id}/`. The compiler workstream
//! (WS-B) is expected to take this same shape and broaden it (multi-type
//! ontology, tighter typing). For Feature-1 / Beat-4 of the demo this is
//! enough: artifacts are real files on disk, classification metadata
//! propagates, and they're directly consumable by the runtime workstream.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::ast::{
    Change, Field, OntologyChangeProposal, OntologyType, PolicyClass, ProtoType, TypeRef,
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArtifactManifest {
    pub proposal_id: String,
    pub directory: String,
    pub proto: String,
    pub ddl: String,
    pub handler: String,
    pub openfga: String,
}

pub fn emit_all(proposal: &OntologyChangeProposal, root: &Path) -> Result<ArtifactManifest> {
    let dir: PathBuf = root.join(&proposal.id);
    fs::create_dir_all(&dir)
        .with_context(|| format!("creating generated dir {}", dir.display()))?;

    let target = proposal.target();
    let snake = snake_case(&target.name);

    let proto_path = dir.join(format!("{snake}.proto"));
    let ddl_path = dir.join(format!("{snake}.sql"));
    let handler_path = dir.join(format!("{snake}_handler.rs"));
    let fga_path = dir.join(format!("{snake}.fga.json"));

    fs::write(&proto_path, render_proto(proposal, &target))?;
    fs::write(&ddl_path, render_ddl(proposal, &target))?;
    fs::write(&handler_path, render_handler(proposal, &target))?;
    fs::write(&fga_path, render_openfga(proposal, &target))?;

    Ok(ArtifactManifest {
        proposal_id: proposal.id.clone(),
        directory: dir.to_string_lossy().into_owned(),
        proto: proto_path.to_string_lossy().into_owned(),
        ddl: ddl_path.to_string_lossy().into_owned(),
        handler: handler_path.to_string_lossy().into_owned(),
        openfga: fga_path.to_string_lossy().into_owned(),
    })
}

// -------- proto --------

fn render_proto(p: &OntologyChangeProposal, target: &TypeRef) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by Agora — DO NOT EDIT.\n\
         // Proposal: {}\n\
         // Source: {:?} → {:?}\n\
         // Compatibility: shape={:?} semantic={:?} policy={:?}\n\
         syntax = \"proto3\";\n\
         package {};\n\n\
         import \"google/protobuf/timestamp.proto\";\n\n",
        p.id,
        p.semantic_contract.meaning_before,
        p.semantic_contract.meaning_after,
        p.compatibility.shape,
        p.compatibility.semantic,
        p.compatibility.policy,
        target.namespace
    ));

    // We render the *post-change* shape of the target type, taking the
    // seed type (if any) as the baseline. For Feature 1's demo we don't
    // have a registry handy at codegen time, so we render the delta as a
    // partial message — clearly tagged.
    match &p.change {
        Change::CreateType { spec } => {
            out.push_str(&render_proto_message(spec));
        }
        Change::AddField { field, .. } => {
            out.push_str(&format!(
                "// PARTIAL — extension of `{name}`. Compiler will merge with baseline.\n\
                 message {name} {{\n\
                    \x20 // existing fields elided\n",
                name = target.name
            ));
            push_proto_field(&mut out, field);
            out.push_str("}\n");
        }
        Change::AddRelation { relation } => {
            out.push_str(&format!(
                "// PARTIAL — relation added to `{name}`. Modeled as a repeated ref field.\n\
                 message {name} {{\n\
                    \x20 // existing fields elided\n\
                    \x20 repeated {to_fqn} {rel_name} = {num} [(agora.relation_cardinality) = \"{card:?}\"];\n\
                 }}\n",
                name = target.name,
                to_fqn = relation.to.fqn().replace('.', "_"),
                rel_name = snake_case(&relation.name),
                num = 901, // synthetic high field number for partial proto
                card = relation.cardinality
            ));
        }
        Change::DeprecateField { field_name, .. } => {
            out.push_str(&format!(
                "// PARTIAL — deprecate `{field_name}` on `{name}`.\n\
                 // Compiler must mark the corresponding field `deprecated = true` and\n\
                 // emit a reserved-name entry once retirement window elapses.\n\
                 message {name} {{\n  reserved \"{field_name}\";\n}}\n",
                name = target.name
            ));
        }
        Change::ReclassifyField {
            field_name, to, ..
        } => {
            out.push_str(&format!(
                "// PARTIAL — reclassify `{field_name}` on `{name}` to {to:?}.\n\
                 message {name} {{\n  \
                    // (agora.classification) updated to {to:?} for `{field_name}`\n}}\n",
                name = target.name
            ));
        }
    }
    out
}

fn render_proto_message(spec: &OntologyType) -> String {
    let mut out = String::new();
    if let Some(doc) = &spec.doc {
        out.push_str(&format!("// {}\n", doc));
    }
    out.push_str(&format!("message {} {{\n", spec.name));
    for f in &spec.fields {
        push_proto_field(&mut out, f);
    }
    out.push_str("}\n");
    out
}

fn push_proto_field(out: &mut String, f: &Field) {
    let ty = proto_type_to_str(&f.proto_type);
    let class = classification_str(&f.classification);
    if let Some(d) = &f.doc {
        out.push_str(&format!("  // {}\n", d));
    }
    out.push_str(&format!(
        "  {req}{ty} {name} = {num} [(agora.classification) = \"{class}\", (agora.since_version) = {since}];\n",
        req = if f.required { "" } else { "optional " },
        ty = ty,
        name = f.name,
        num = f.proto_number,
        class = class,
        since = f.since_version
    ));
}

fn proto_type_to_str(t: &ProtoType) -> String {
    match t {
        ProtoType::String => "string".into(),
        ProtoType::Int64 => "int64".into(),
        ProtoType::Bool => "bool".into(),
        ProtoType::Bytes => "bytes".into(),
        ProtoType::Timestamp => "google.protobuf.Timestamp".into(),
        ProtoType::Ref(s) => s.replace('.', "_"),
    }
}

fn classification_str(c: &PolicyClass) -> &'static str {
    match c {
        PolicyClass::Public => "PUBLIC",
        PolicyClass::Internal => "INTERNAL",
        PolicyClass::Sensitive => "SENSITIVE",
        PolicyClass::Pii => "PII",
    }
}

// -------- DDL --------

fn render_ddl(p: &OntologyChangeProposal, target: &TypeRef) -> String {
    let table = format!("{}_{}", snake_case(&target.namespace.replace('.', "_")), snake_case(&target.name));
    let mut out = String::new();
    out.push_str(&format!(
        "-- Generated by Agora — DO NOT EDIT.\n\
         -- Proposal: {pid}\n\
         -- Compatibility (storage): {storage:?}\n\n",
        pid = p.id,
        storage = p.compatibility.storage
    ));
    match &p.change {
        Change::CreateType { spec } => {
            out.push_str(&format!("CREATE TABLE IF NOT EXISTS {} (\n", table));
            out.push_str("  entity_id TEXT PRIMARY KEY,\n");
            for (i, f) in spec.fields.iter().enumerate() {
                let comma = if i + 1 < spec.fields.len() { "," } else { "" };
                out.push_str(&format!(
                    "  {col_name} {col_type} {nullable}{comma}  -- classification={class:?}\n",
                    col_name = f.name,
                    col_type = ddl_type(&f.proto_type),
                    nullable = if f.required { "NOT NULL" } else { "NULL" },
                    class = f.classification
                ));
            }
            out.push_str(");\n");
            for f in &spec.fields {
                if matches!(f.classification, PolicyClass::Sensitive | PolicyClass::Pii) {
                    out.push_str(&format!(
                        "COMMENT ON COLUMN {table}.{col} IS 'agora.classification={class:?}';\n",
                        col = f.name,
                        class = f.classification
                    ));
                }
            }
        }
        Change::AddField { field, .. } => {
            out.push_str(&format!(
                "ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {col} {ty} {nullable}; -- classification={class:?}\n",
                col = field.name,
                ty = ddl_type(&field.proto_type),
                nullable = if field.required { "NOT NULL DEFAULT NULL" } else { "NULL" },
                class = field.classification
            ));
            if matches!(field.classification, PolicyClass::Sensitive | PolicyClass::Pii) {
                out.push_str(&format!(
                    "COMMENT ON COLUMN {table}.{col} IS 'agora.classification={class:?}';\n",
                    col = field.name,
                    class = field.classification
                ));
            }
        }
        Change::AddRelation { relation } => {
            let join = format!(
                "{}_rel_{}",
                table,
                snake_case(&relation.name)
            );
            out.push_str(&format!(
                "CREATE TABLE IF NOT EXISTS {join} (\n  \
                 from_id TEXT NOT NULL,\n  \
                 to_id   TEXT NOT NULL,\n  \
                 PRIMARY KEY (from_id, to_id)\n);\n\
                 -- cardinality: {card:?}\n",
                card = relation.cardinality
            ));
        }
        Change::DeprecateField { field_name, .. } => {
            out.push_str(&format!(
                "-- Deprecate column {field_name} (no DROP yet; deprecation window).\n\
                 COMMENT ON COLUMN {table}.{field_name} IS 'DEPRECATED via proposal {pid}';\n",
                pid = p.id,
            ));
        }
        Change::ReclassifyField {
            field_name, to, ..
        } => {
            out.push_str(&format!(
                "COMMENT ON COLUMN {table}.{field_name} IS 'agora.classification={to:?}';\n"
            ));
        }
    }
    out
}

fn ddl_type(t: &ProtoType) -> &'static str {
    match t {
        ProtoType::String => "TEXT",
        ProtoType::Int64 => "BIGINT",
        ProtoType::Bool => "BOOLEAN",
        ProtoType::Bytes => "BYTEA",
        ProtoType::Timestamp => "TIMESTAMPTZ",
        ProtoType::Ref(_) => "TEXT", // FK by id, kept simple
    }
}

// -------- HTTP handler skeleton --------

fn render_handler(p: &OntologyChangeProposal, target: &TypeRef) -> String {
    let module = snake_case(&target.name);
    let mod_path = format!("{}::{}", target.namespace.replace('.', "::"), target.name);

    format!(
        "//! Generated by Agora — proposal {pid}.\n\
         //! HTTP handler skeleton for `{fqn}`. The compiler/runtime workstream\n\
         //! is expected to plumb storage; this file establishes the route shape.\n\n\
         use axum::{{extract::State, Json, http::StatusCode, response::IntoResponse}};\n\
         use serde::{{Deserialize, Serialize}};\n\n\
         /// POST /entities/{module}\n\
         #[derive(Debug, Deserialize)]\n\
         pub struct Create{type_name}Cmd {{\n  \
            pub entity_id: String,\n  \
            // generated fields would go here\n\
         }}\n\n\
         #[derive(Debug, Serialize)]\n\
         pub struct Create{type_name}Resp {{\n  \
            pub entity_id: String,\n  \
            pub ontology_version: u32,\n\
         }}\n\n\
         pub async fn create_{module}(\n  \
            State(_state): State<crate::AppState>,\n  \
            Json(cmd): Json<Create{type_name}Cmd>,\n\
         ) -> impl IntoResponse {{\n  \
            // TODO(runtime): write to mutation_log with ontology_version stamp.\n  \
            // For now, echo. Compatibility (api): {api:?}.\n  \
            (StatusCode::CREATED, Json(Create{type_name}Resp {{\n    \
                entity_id: cmd.entity_id,\n    \
                ontology_version: {ver},\n  \
            }}))\n\
         }}\n\n\
         /// Route registrar — called from `api::router()`.\n\
         pub fn routes() -> axum::Router<crate::AppState> {{\n  \
            axum::Router::new()\n    \
                .route(\"/entities/{module}\", axum::routing::post(create_{module}))\n\
         }}\n\n\
         // module path: {mod_path}\n",
        pid = p.id,
        fqn = target.fqn(),
        type_name = target.name,
        module = module,
        api = p.compatibility.api,
        ver = next_version(&p.change),
        mod_path = mod_path,
    )
}

fn next_version(change: &Change) -> u32 {
    match change {
        Change::CreateType { spec } => spec.version,
        Change::AddField { field, .. } => field.since_version,
        Change::AddRelation { relation } => relation.since_version,
        _ => 2,
    }
}

// -------- OpenFGA tuples --------

fn render_openfga(p: &OntologyChangeProposal, target: &TypeRef) -> String {
    // Emit a small JSON document containing:
    //   - the FGA "type" the runtime should register for this concept
    //   - example tuples for each PolicyClass the proposal touches.
    // This matches STACK.md Artifact 3 (classification-propagation contract).
    let fqn = target.fqn();
    let fga_type = snake_case(&target.name);

    // Collect the classifications this proposal exposes — used to pick
    // which canonical tuples to emit.
    let mut classes: Vec<PolicyClass> = Vec::new();
    match &p.change {
        Change::AddField { field, .. } => classes.push(field.classification.clone()),
        Change::ReclassifyField { to, .. } => classes.push(to.clone()),
        Change::CreateType { spec } => {
            for f in &spec.fields {
                if !classes.contains(&f.classification) {
                    classes.push(f.classification.clone());
                }
            }
            if classes.is_empty() {
                classes.push(spec.policy_class.clone());
            }
        }
        _ => classes.push(PolicyClass::Internal),
    }

    let tuples: Vec<serde_json::Value> = classes
        .iter()
        .filter_map(|c| canonical_tuple(c, &fga_type, &p.ownership.team))
        .collect();

    let model = json!({
        "version": "1.1",
        "schema_version": "1.1",
        "type_definitions": [
            {
                "type": fga_type,
                "relations": {
                    "owner":             { "this": {} },
                    "internal_viewer":   { "this": {} },
                    "sensitive_viewer":  { "this": {} },
                    "pii_viewer":        { "this": {} }
                },
                "metadata": {
                    "relations": {
                        "owner":             { "directly_related_user_types": [{"type": "team"}] },
                        "internal_viewer":   { "directly_related_user_types": [{"type": "team", "wildcard": {}}] },
                        "sensitive_viewer":  { "directly_related_user_types": [{"type": "team"}] },
                        "pii_viewer":        { "directly_related_user_types": [{"type": "role"}] }
                    }
                }
            }
        ]
    });

    serde_json::to_string_pretty(&json!({
        "proposal_id": p.id,
        "concept_fqn": fqn,
        "model": model,
        "tuples": tuples,
    }))
    .unwrap()
}

fn canonical_tuple(
    class: &PolicyClass,
    fga_type: &str,
    owner_team: &str,
) -> Option<serde_json::Value> {
    Some(match class {
        PolicyClass::Public => return None,
        PolicyClass::Internal => json!({
            "object":   format!("{fga_type}:{{id}}"),
            "relation": "internal_viewer",
            "user":     "team:*"
        }),
        PolicyClass::Sensitive => json!({
            "object":   format!("{fga_type}:{{id}}"),
            "relation": "sensitive_viewer",
            "user":     format!("team:{owner_team}")
        }),
        PolicyClass::Pii => json!({
            "object":   format!("{fga_type}:{{id}}"),
            "relation": "pii_viewer",
            "user":     "role:dpo"
        }),
    })
}

// -------- utilities --------

fn snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else if ch == '.' || ch == '-' || ch == ' ' {
            out.push('_');
        } else {
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::llm::mock_proposal_from_prompt;

    #[test]
    fn emit_all_writes_four_files() {
        let prop = mock_proposal_from_prompt(
            "users need biometric login on mobile",
            "user://test",
            "prop_test123".into(),
        );
        let tmp = tempdir();
        let m = emit_all(&prop, &tmp).expect("emit_all");
        for path in [&m.proto, &m.ddl, &m.handler, &m.openfga] {
            let content = std::fs::read_to_string(path).expect("read artifact");
            assert!(!content.is_empty(), "empty artifact: {}", path);
        }
        // Sanity: OpenFGA artifact is valid JSON.
        let raw = std::fs::read_to_string(&m.openfga).unwrap();
        let _: serde_json::Value = serde_json::from_str(&raw).expect("openfga json");
        std::fs::remove_dir_all(tmp).ok();
    }

    fn tempdir() -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "agora-test-{}",
            chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0)
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }
}
